name: spstats
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.0
  - attrs=19.3.0
  - backcall=0.1.0
  - bleach=3.1.1
  - boost-cpp=1.70.0
  - bzip2=1.0.8
  - ca-certificates=2019.11.28
  - cairo=1.16.0
  - certifi=2019.11.28
  - cfitsio=3.470
  - click-plugins=1.1.1
  - curl=7.68.0
  - cycler=0.10.0
  - dbus=1.13.6
  - decorator=4.4.1
  - defusedxml=0.6.0
  - entrypoints=0.3
  - expat=2.2.9
  - fiona=1.8.13
  - fontconfig=2.13.1
  - freetype=2.10.0
  - freexl=1.0.5
  - gdal=3.0.4
  - geopandas=0.7.0
  - geos=3.8.0
  - geotiff=1.5.1
  - gettext=0.19.8.1
  - giflib=5.2.1
  - glib=2.58.3
  - hdf4=4.2.13
  - hdf5=1.10.5
  - icu=64.2
  - importlib_metadata=1.5.0
  - ipykernel=5.1.4
  - ipython=7.12.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.16.0
  - jinja2=2.11.1
  - jpeg=9c
  - json-c=0.13.1
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.0.0
  - jupyter_console=6.0.0
  - jupyter_core=4.6.3
  - kealib=1.4.10
  - kiwisolver=1.1.0
  - krb5=1.16.4
  - libblas=3.8.0
  - libcblas=3.8.0
  - libclang=9.0.1
  - libcurl=7.68.0
  - libcxx=9.0.1
  - libdap4=3.20.4
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgdal=3.0.4
  - libgfortran=4.0.0
  - libiconv=1.15
  - libkml=1.3.0
  - liblapack=3.8.0
  - libllvm9=9.0.1
  - libnetcdf=4.7.3
  - libopenblas=0.3.8
  - libpng=1.6.37
  - libpq=12.2
  - libsodium=1.0.17
  - libspatialindex=1.9.3
  - libspatialite=4.3.0a
  - libssh2=1.8.2
  - libtiff=4.1.0
  - libwebp=1.0.2
  - libxml2=2.9.10
  - llvm-openmp=9.0.1
  - lz4-c=1.8.3
  - markupsafe=1.1.1
  - matplotlib=3.1.3
  - matplotlib-base=3.1.3
  - mistune=0.8.4
  - munch=2.5.0
  - nbconvert=5.6.1
  - nbformat=5.0.4
  - ncurses=6.1
  - notebook=6.0.3
  - nspr=4.20
  - nss=3.47
  - numpy=1.18.1
  - openjpeg=2.3.1
  - openssl=1.1.1d
  - pandas=1.0.1
  - pandoc=2.9.2
  - pandocfilters=1.4.2
  - parso=0.6.1
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=20.0.2
  - pixman=0.38.0
  - poppler=0.67.0
  - poppler-data=0.4.9
  - postgresql=12.2
  - proj=6.3.1
  - prometheus_client=0.7.1
  - prompt_toolkit=2.0.10
  - ptyprocess=0.6.0
  - pygments=2.5.2
  - pyparsing=2.4.6
  - pyproj=2.5.0
  - pyqt=5.12.3
  - pyrsistent=0.15.7
  - python=3.7.6
  - python-dateutil=2.8.1
  - pytz=2019.3
  - pyzmq=19.0.0
  - qt=5.12.5
  - qtconsole=4.6.0
  - readline=8.0
  - rtree=0.9.4
  - scipy=1.4.1
  - send2trash=1.5.0
  - setuptools=45.2.0
  - shapely=1.7.0
  - six=1.14.0
  - sqlite=3.30.1
  - tbb=2018.0.5
  - terminado=0.8.3
  - testpath=0.4.4
  - tiledb=1.7.0
  - tk=8.6.10
  - tornado=6.0.3
  - traitlets=4.3.3
  - tzcode=2019a
  - wcwidth=0.1.8
  - webencodings=0.5.1
  - wheel=0.34.2
  - widgetsnbextension=3.5.1
  - xerces-c=3.2.2
  - xz=5.2.4
  - zeromq=4.3.2
  - zipp=3.0.0
  - zlib=1.2.11
  - zstd=1.4.4
  - pip:
    - affine==2.3.0
    - astunparse==1.6.3
    - autopep8==1.5
    - beniget==0.2.0
    - click==7.0
    - cligj==0.5.0
    - gast==0.3.3
    - pycodestyle==2.5.0
    - pylandstats==2.0.0
    - pyqt5-sip==4.19.18
    - pyqtwebengine==5.12.1
    - rasterio==1.1.3
    - snuggs==1.4.7
    - transonic==0.4.2

